services: 

  server:
    build: 
      context: server
    container_name: server
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks: 
      - node-network



  admin:
    build:
      context: client-admin
    ports:
      - '3001:3000'
    stdin_open: true
    networks: 
      - node-network
    volumes:
      - ./client-admin:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  customer:
    build:
      context: client-customer
    ports:
      - '3002:3000'
    stdin_open: true
    networks: 
      - node-network
    volumes:
      - ./client-customer:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  cors:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cors
    ports:
      - "1707:80"

      
networks: 
  node-network:
    driver: bridge 

  
